### ISSUE TITLE
How rebuild the project in protobuf 2.5.0

### ISSUE THREAD

**Issue by wzp06354** [wdtinc/mapbox-vector-tile-java#11]
I run the jar in hadoop 2.7.1 and the version of protobuf in hadoop is 2.5.0.Can i or how to rebuild the project and generate new jars in protobuf 2.5.0

**Comment by ShibaBandit** [comment]
You could look into using https://maven.apache.org/plugins/maven-shade-plugin/. If I'm remembering correctly, <dependencyManagement/> won't be an option since you need the protobuf implementation to be the same as the version that generated the code.

**Comment by wzp06354** [comment]
I have rebuilding the project by protobuf 2.5.0.I have change some params class type in some function.Now i don't test it.I will try it with maven-shade-plugin.
