### ISSUE TITLE
Android API Level 15 compatibility

### ISSUE THREAD

**Issue by boldtrn** [wdtinc/mapbox-vector-tile-java#17]
As discussed in #14, it would be great to support Android versions down to API level 15, if possible, as mentioned by @devemux86.

According to @snodnipper, it looks like we have some uses of the static methods in java.util.Objects, which are available above API 19 (Android 4.4.+).

https://github.com/wdtinc/mapbox-vector-tile-java/blob/933fa04e2cc5629bfc1b99582da8ab170535b702/src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/TileGeomResult.java#L30

https://github.com/wdtinc/mapbox-vector-tile-java/blob/933fa04e2cc5629bfc1b99582da8ab170535b702/src/main/java/com/wdtinc/mapbox_vector_tile/adapt/jts/UserDataKeyValueMapConverter.java#L39

I am not sure what else needs to be done and if these method calls can be easily converted to Android API level 15 compatibility? If it's just these [`Objects.requireNonNull`](https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#requireNonNull(T)) calls, I can create a PR adding a Util Method like:

```
requireNonNull(Object obj)
   if(obj == null)
      throw new NullPointException();
```

**Comment by snodnipper** [comment]
I'll try and take a look this weekend.  It actually looked quite hard to even get a legacy emulator working earlier in the latest Android Studio (macOS).

If you are set up to go then you are most welcome to investigate 👍

**Comment by boldtrn** [comment]
I don't really have a well setup Android dev environment, sorry, so I cannot really test different version etc. :).

**Comment by boldtrn** [comment]
I was able to run this library using Android Emulator on API level 16 (Android 4.1.2).

**Comment by devemux86** [comment]
I tested latest `master` with our [VTM](https://github.com/mapsforge/vtm) map library on Android emulator API 16 and all seem to work!
A bit strange since there are API 19 calls in code or they're in non accessible places?

Could not test on API 15, since Android emulator doesn't work ok most of time.
Also [Genymotion](https://www.genymotion.com/) offers VMs with min API 16.

**Comment by snodnipper** [comment]
^ I suspect all will be fine until you reach one of the code paths touching anything unavailable.  I tried writing some tiles yesterday against API 16 and ran into the issues.

**Comment by devemux86** [comment]
> I tried writing some tiles

My tests were only for decoding MVT tiles, not any encoding.

**Comment by boldtrn** [comment]
> I suspect all will be fine until you reach one of the code paths touching anything unavailable.

This would be pretty unfortunate. But it also makes sense. AFAIK Android allows you to check the SDK version and only enter a code block if the current SDK has at least a certain level. Therefore Android has to compile code even if it's not runnable on the SDK version.

Is there a good way to find method calls that are not compatible with the current SDK version?

**Comment by ShibaBandit** [comment]
You could try running the unit tests on your android device or emulator?

**Comment by boldtrn** [comment]
> You could try running the unit tests on your android device or emulator?

Yes this would be probably possible, but I assume the tests don't have 100% coverage, so we don't really know if the code might crash at some point? Running the tests would definitely, but it's a pity that there is  static analysis that will just tell you. I guess our best guess at the moment would be to convert your library to an Android project, setting the SDK version on it, because then, Android Studio will tell you if you use methods that are not suitable for the chosen SDK version.

**Comment by boldtrn** [comment]
Ok I just converted this project to an Android project with language level 15. There were two types of error, one were I think about different Java version, available during the compilation (see this [commit](https://github.com/boldtrn/mapbox-vector-tile-java/commit/ba279cacb4ff3775a77137433764e50f023935a6)), the other errors were about the API level, essentially there were a couple of `Objects.requireNonNull` and one try with resource statement (see this [commit](https://github.com/boldtrn/mapbox-vector-tile-java/commit/1b95b20676751f55e212bab07783c99ad551804d)). If you don't mind, I would just create a PR fixing the requireNonNull by creating a Helper method and converting the try with resource to a traditional try like:

```
        // try with resources requires api level 19
        InputStream is = null;
        try {
            is = new FileInputStream(file);
            jtsMvt = loadMvt(is, geomFactory, tagConverter, ringClassifier);
        }finally {
            if(is != null){
                is.close();
            }
        }
```

Also, if you don't mind I would also change the two Java language errors? I think it would not hurt to convert them, even though I don't think it is necessary.

**Comment by ShibaBandit** [comment]
Will look into getting new version pushed to maven central tomorrow.

**Comment by Gustl22** [comment]
Is there any chance to get the current jar files? Maybe as a Snapshot.. [Maven](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.wdtinc%22%20AND%20a%3A%22mapbox-vector-tile%22) doesn't provide them yet. Sorry for asking. Don't know the release requirements :) Thx

**Comment by ShibaBandit** [comment]
Pushed maven 3.0.0 release. Might take a while for it to show up.

**Comment by devemux86** [comment]
Thank you all for that fine result!
We can now use in [VTM](https://github.com/mapsforge/vtm) vector map library the latest `mapbox-vector-tile` release without Android constraints. 🙂
