### ISSUE TITLE
Issue with mvt generation for polygon geometry

### ISSUE THREAD

**Issue by coder123456** [wdtinc/mapbox-vector-tile-java#26]
Having a strange issue with the generation of mvt for osm building polygon. The mvt polygon contains additional segments. I am using the same code as in the testcase to build the mvt geom. 

Original geometry
![original_geom](https://user-images.githubusercontent.com/35495048/40315923-6a4f5894-5d3a-11e8-803c-8459b3a633bb.png)

This is the mvt  at zoom level 18
![zoom_level_18](https://user-images.githubusercontent.com/35495048/40315622-84f5a578-5d39-11e8-8617-a15a4a6f5470.png)

Zooming further you will find more segments getting added

![zoom_level_19](https://user-images.githubusercontent.com/35495048/40316109-d86a6418-5d3a-11e8-91f4-ca69ff9f4f27.png)

The WKT is as follows

MULTIPOLYGON (((545718.1333394476 6866923.365958172, 545718.9237078322 6866923.839977133, 545720.1816180766 6866924.386922123, 545721.0721740036 6866924.623931634, 545721.9849938283 6866924.76978364, 545722.8978136531 6866924.806246642, 545724.2670433887 6866924.660394636, 545725.591745329 6866924.295764623, 545726.4377734606 6866923.912903129, 545727.6066281144 6866923.20187469, 545728.3190728544 6866922.600235288, 545728.9535939523 6866921.9439014485, 545729.5101914057 6866921.21464169, 545729.7550942858 6866920.813548851, 545730.1892402992 6866920.01136323, 545730.3673514862 6866919.5738074705, 545730.6456502129 6866918.698696026, 545730.834893346 6866917.805353191, 545730.9128169907 6866916.875547487, 545730.9128169907 6866916.419760417, 545730.834893346 6866915.508186351, 545730.6679141106 6866914.59661239, 545730.3896153839 6866913.721501486, 545730.0111291149 6866912.882853623, 545729.5435872523 6866912.080668792, 545728.9981217477 6866911.351409927, 545728.3636006496 6866910.676845537, 545727.2949335384 6866909.819966524, 545726.5045651537 6866909.345948387, 545725.2243910116 6866908.817235879, 545724.3338350846 6866908.598458301, 545722.9646053461 6866908.43437512, 545722.0517855214 6866908.470838053, 545721.1389656995 6866908.598458301, 545719.8142637592 6866908.981319068, 545718.9793675764 6866909.364179853, 545717.8995685162 6866907.522801962, 545735.9667218718 6866895.307731575, 545728.0964338719 6866883.566696301, 545707.9810018872 6866897.149106668, 545702.760117768 6866889.929460188, 545696.359247049 6866881.050762402, 545706.0774385931 6866873.411808483, 545703.1497359859 6866869.637912684, 545684.2365545015 6866845.244367993, 545640.4212029236 6866788.891551351, 545645.7868023807 6866777.515294569, 545645.4862397563 6866777.332982891, 545646.6773583078 6866775.38224821, 545648.1467755858 6866775.45517286, 545648.3026228724 6866775.291092397, 545621.6972645724 6866758.7554446785, 545621.6304728794 6866758.974218186, 545622.365181517 6866760.268628228, 545620.4727501745 6866763.34968959, 545617.2110890936 6866762.146434719, 545617.8010823934 6866758.627826799, 545619.2816316232 6866758.080893068, 545619.3484233161 6866757.880350706, 545588.3459451309 6866753.286108915, 545588.3682090285 6866753.450188931, 545589.4480080887 6866754.4346691165, 545588.9470703824 6866757.898581829, 545585.5740898103 6866758.080893068, 545584.6724019343 6866754.616980275, 545585.7744648921 6866753.559575613, 545585.7633329433 6866753.340802252, 545555.4732995008 6866761.30780264, 545555.5734870404 6866761.508345085, 545556.9538487276 6866761.927661125, 545557.8221407542 6866765.37334592, 545554.8387784028 6866766.868299566, 545552.6457844331 6866764.0060105035, 545553.2246457869 6866762.675137593, 545553.1244582445 6866762.474595118, 545528.411531287 6866781.72669545, 545528.6119063718 6866781.872544867, 545530.0034000052 6866781.635539561, 545532.2409217701 6866784.516066072, 545530.0367958545 6866787.104894575, 545526.9198501112 6866785.336469381, 545526.9532459578 6866783.896205848, 545526.7862667224 6866783.750356394, 545511.6802118206 6866811.188332018, 545511.8249271584 6866811.206563262, 545513.0605735079 6866810.495544769, 545516.255442893 6866812.191050503, 545515.242435526 6866815.472675521, 545511.6134201275 6866815.108050453, 545511.0902185207 6866813.777169095, 545510.8787114872 6866813.704244098, 545507.8730852351 6866844.916204217, 545508.0957242176 6866844.897972898, 545508.8638287046 6866843.676474521, 545512.4260524099 6866843.949944292, 545512.7934067302 6866847.450358159, 545510.4890932692 6866848.908864386, 545510.054947256 6866848.270767879, 545509.2311830248 6866848.817707736, 545511.4464408922 6866852.081116338, 545508.1068561665 6866854.360033744, 545501.1493879913 6866843.89525034, 545491.4311964471 6866850.403833543, 545480.6443377888 6866857.641675941, 545487.6574657082 6866868.142939957, 545480.9894282086 6866872.609627583, 545454.7180283823 6866833.339324052, 545446.8254764846 6866838.517013281, 545446.346802676 6866837.787761077, 545459.0483565745 6866829.200821329, 545458.5362869166 6866828.471569965, 545393.5034403963 6866872.354388225, 545420.8212434362 6866913.138094266, 545405.6038690461 6866923.402421167, 545415.3109286414 6866937.87824368, 545481.8243243913 6867037.09484589, 545478.2287048395 6867039.537901499, 545480.2547195709 6867042.527910863, 545484.0952420029 6867048.216224419, 545487.6908615547 6867045.7731661815, 545505.7914107596 6867072.7380067445, 545521.0533129451 6867062.473489517, 545531.16112271 6867055.600098971, 545644.5622879828 6866979.245693495, 545653.1784165691 6866973.356880924, 545715.7622342936 6866931.187274624, 545712.8122677859 6866926.811712037, 545715.3948799734 6866924.988561657, 545718.044283854 6866923.293032177, 545718.1333394476 6866923.365958172)))

**Comment by ShibaBandit** [comment]
Did you buffer the clipping boundaries outside the tile like in the readme? What are you rendering/styling with?

**Comment by ShibaBandit** [comment]
Details - https://github.com/wdtinc/mapbox-vector-tile-java#buffering-polygons-beyond-mvt-extent

If you can verify this isn't the issue, I can investigate further.

**Comment by coder123456** [comment]
Adding the buffer did the trick. The polygon geometries render fine now. Thanks so much for the help.
