### ISSUE TITLE
Issue with mvt generation for line geometry

### ISSUE THREAD

**Issue by coder123456** [wdtinc/mapbox-vector-tile-java#27]
Found an issue while rendering the osm roads layer. Some of the line geometries does not render properly at lower zoom levels specially where the line segments form a ring.

**Original geometry**
![original_line_geom](https://user-images.githubusercontent.com/35495048/40401825-0caa0e14-5e66-11e8-9d59-f2740454f97d.png)

**MVT Geometry**
![mvt_geometry](https://user-images.githubusercontent.com/35495048/40401882-64583104-5e66-11e8-8c59-657b24cf58ca.png)

**Original geometry WKT**
MULTILINESTRING ((545022.4644456336 6867178.738599846, 545023.7891475739 6867185.429774573, 545024.813286887 6867190.64415437, 545029.8894556686 6867190.206583908, 545036.2791944387 6867192.339740138, 545040.0751890754 6867195.7309127385, 545042.7913846518 6867201.255245361, 545043.1476070203 6867206.34201043, 545042.4574261782 6867209.477938888, 545040.03066128 6867213.944815833, 545037.4591810413 6867216.4608537285, 545032.939609716 6867218.794570745, 545028.5536217794 6867219.469160945, 545023.5331127449 6867218.5757847475, 545020.4606947971 6867217.026050759, 545015.5960330492 6867211.611100222, 545014.0486921292 6867206.761349631, 545014.1488796688 6867202.185083897, 545016.5088528739 6867196.4966615895, 545020.0822085281 6867192.868471254, 545024.813286887 6867190.64415437))

**Comment by coder123456** [comment]
Is there a fix planned for this issue ?

**Comment by miyuer** [comment]
In JtsAdapter Class, linesToGeomCmds methond `  // Check geometry for repeated end points
        final int repeatEndCoordCount = countCoordRepeatReverse(geomCoords);
        int minExpGeomCoords = geomCoords.length - repeatEndCoordCount;

        // Guard/Optimization: Not enough geometry coordinates for a line
        if(minExpGeomCoords < 2) {
           return Collections.emptyList();
        }
   //add code as below
        if(repeatEndCoordCount > 0){
        	if(repeatEndCoordCount == 1){
        		minExpGeomCoords = geomCoords.length;
        	}else{
        		minExpGeomCoords++;
        	}
        }`

**Comment by miyuer** [comment]
In JtsAdapter Class, linesToGeomCmds method,  add code as below 
`  // Check geometry for repeated end points
        final int repeatEndCoordCount = countCoordRepeatReverse(geomCoords);
        int minExpGeomCoords = geomCoords.length - repeatEndCoordCount;

        // Guard/Optimization: Not enough geometry coordinates for a line
        if(minExpGeomCoords < 2) {
           return Collections.emptyList();
        }
        //add code as below
        if(repeatEndCoordCount > 0){
        	if(repeatEndCoordCount == 1){
        		minExpGeomCoords = geomCoords.length;
        	}else{
        		minExpGeomCoords++;
        	}
        }`

**Comment by ShibaBandit** [comment]
Closing as fixed via #40
