### ISSUE TITLE
Upgrade to locationtech JTS core 1.16.1

### ISSUE THREAD

**Issue by ShibaBandit** [wdtinc/mapbox-vector-tile-java#32]
Upgrade to latest JTS core release of 1.16.1.

**Comment by ShibaBandit** [comment]
Closed via #33

**Comment by devemux86** [comment]
Note that there are reports that JTS 1.16 requires latest Android 7 Nougat (API 24):

```java
D8: Default interface methods are only supported starting with Android N (--min-api 24):
org.locationtech.jts.geom.Coordinate org.locationtech.jts.geom.CoordinateSequence.createCoordinate()
```

See also https://github.com/locationtech/jts/issues/145

That's why several projects remain still on JTS 1.15 to maintain Android compatibility, like VTM and GraphHopper.

**Comment by ShibaBandit** [comment]
@devemux86 Thank you for bringing this to my attention. I wanted to upgrade to the latest JTS to get all of the bug fixes. I think it's safe to do <dependencyManagement/> to sub out the JTS core version to 1.15 also in any downstream builds as a work around. Let me think on this if I should revert to 1.15 or 1.15.1.

**Comment by devemux86** [comment]
> Let me think on this if I should revert to 1.15 or 1.15.1.

We have tested JTS 1.15.1 successfully also on older Android. :slightly_smiling_face: 
https://github.com/graphhopper/graphhopper/pull/1507

**Comment by ShibaBandit** [comment]
Reading that locationtech link, it doesn't sound like they are doing any android workarounds anytime soon. Reverting would still be a net upgrade from 1.15 to 1.15.1... might do that here in a bit because I don't want to upset the android users.

**Comment by ShibaBandit** [comment]
Will close this and make a new issue for 1.15.1
